#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppAngie.Resource", IsApplication=true)]

namespace AppAngie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int jump_09_0000_min = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int jump_09_0001_min = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int jump_09_0002_min = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int jump_09_0003_min = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int jump_09_0004_min = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int jump_09_0005_min = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int jump_09_0006_min = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int jump_09_0007_min = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int jump_09_0008_min = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int jump_09_0009_min = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int jump_09_0010_min = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int jump_09_0011_min = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int jump_09_0012_min = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int jump_09_0013_min = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int jump_09_0014_min = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int jump_09_0015_min = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int kiss_01_0000_min = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int kiss_01_0001_min = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int kiss_01_0002_min = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int kiss_01_0003_min = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int kiss_01_0004_min = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int kiss_01_0005_min = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int kiss_01_0006_min = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int kiss_01_0007_min = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int kiss_01_0008_min = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int kiss_01_0009_min = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int kiss_01_0010_min = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int kiss_01_0011_min = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int kiss_01_0012_min = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int kiss_01_0013_min = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int kiss_01_0014_min = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int kiss_01_0015_min = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int kiss_02_0000_min = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int kiss_02_0001_min = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int kiss_02_0002_min = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int kiss_02_0003_min = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int kiss_02_0004_min = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int kiss_02_0005_min = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int kiss_02_0006_min = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int kiss_02_0007_min = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int kiss_02_0008_min = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int kiss_02_0009_min = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int kiss_02_0010_min = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int kiss_02_0011_min = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int kiss_02_0012_min = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int kiss_02_0013_min = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int kiss_02_0014_min = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int kiss_02_0015_min = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int kiss_back_03_0000_min = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int kiss_back_03_0001_min = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int kiss_back_03_0002_min = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int kiss_back_03_0003_min = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int kiss_back_03_0004_min = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int kiss_back_03_0005_min = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int kiss_back_03_0006_min = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int kiss_back_03_0007_min = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int kiss_back_03_0008_min = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int kiss_back_03_0009_min = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int kiss_back_03_0010_min = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int kiss_back_03_0011_min = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int kiss_back_03_0012_min = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int kiss_back_03_0013_min = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int kiss_back_03_0014_min = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int kiss_back_03_0015_min = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int kiss_back_03_0016_min = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int kiss_back_03_0017_min = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int kiss_back_03_0018_min = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int kiss_back_03_0019_min = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int kiss_back_03_0020_min = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int kiss_back_03_0021_min = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int kiss_back_03_0022_min = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int kiss_back_03_0023_min = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int kiss_back_03_0024_min = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int kiss_back_03_0025_min = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int left_hand_poke_04_0000_min = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int left_hand_poke_04_0001_min = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int left_hand_poke_04_0002_min = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int left_hand_poke_04_0003_min = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int left_hand_poke_04_0004_min = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int left_hand_poke_04_0005_min = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int left_hand_poke_04_0006_min = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int left_hand_poke_04_0007_min = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int left_hand_poke_04_0008_min = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int left_hand_poke_04_0009_min = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int left_hand_poke_04_0010_min = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int left_hand_poke_04_0011_min = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int left_hand_poke_04_0012_min = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int left_hand_poke_04_0013_min = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int left_hand_poke_04_0014_min = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int left_hand_poke_04_0015_min = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int left_hand_poke_04_0016_min = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int left_hand_poke_04_0017_min = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int left_hand_poke_04_0018_min = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int left_hand_poke_04_0019_min = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int poke_under_belly_06_0000_min = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int poke_under_belly_06_0001_min = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int poke_under_belly_06_0002_min = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int poke_under_belly_06_0003_min = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int poke_under_belly_06_0004_min = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int poke_under_belly_06_0005_min = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int poke_under_belly_06_0006_min = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int poke_under_belly_06_0007_min = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int poke_under_belly_06_0008_min = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int poke_under_belly_06_0009_min = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int poke_under_belly_06_0010_min = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int poke_under_belly_06_0011_min = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int poke_under_belly_06_0012_min = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int poke_under_belly_06_0013_min = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int poke_under_belly_06_0014_min = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int poke_under_belly_06_0015_min = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int poke_under_belly_06_0016_min = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int poke_under_belly_06_0017_min = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int poke_under_belly_06_0018_min = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int poke_under_belly_06_0019_min = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int pull_shirt_down_0000_min = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int pull_shirt_down_0001_min = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int pull_shirt_down_0002_min = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int pull_shirt_down_0003_min = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int pull_shirt_down_0004_min = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int pull_shirt_down_0005_min = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int pull_shirt_down_0006_min = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int pull_shirt_down_0007_min = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int right_hand_poke_05_0000_min = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int right_hand_poke_05_0001_min = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int right_hand_poke_05_0002_min = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int right_hand_poke_05_0003_min = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int right_hand_poke_05_0004_min = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int right_hand_poke_05_0005_min = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int right_hand_poke_05_0006_min = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int right_hand_poke_05_0007_min = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int right_hand_poke_05_0008_min = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int right_hand_poke_05_0009_min = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int right_hand_poke_05_0010_min = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int right_hand_poke_05_0011_min = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int right_hand_poke_05_0012_min = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int right_hand_poke_05_0013_min = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int right_hand_poke_05_0014_min = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int right_hand_poke_05_0015_min = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int right_hand_poke_05_0016_min = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int right_hand_poke_05_0017_min = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int right_hand_poke_05_0018_min = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int right_hand_poke_05_0019_min = 2130837647;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int animated_android = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int recordStatusTextView = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int soundButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int statusTextView = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int videoButton = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
